### ISSUE TITLE
Netgsm::getAvailablePackages(); Hatası

### ISSUE THREAD

**Issue by kurtulusoz** [tarfin-labs/netgsm#12]
Merhabalar,
 install sonrasında Netgsm::getAvailablePackages() komutu çıktısı **Mesaj metnindeki bir problemden dolayı gönderilemedi veya standart maksimum mesaj karakter sayısını geçtiniz.** vermektedir. Kurulumdan sonra publish ederken de publish edecek dosya bulunamadı hatası vermektedir.

**Comment by hozdemir** [comment]
merhaba

dökümantasyonda küçük bir hata yapmışız. 

`php artisan vendor:publish --provider="TarfinLabs\Netgsm\NetgsmServiceProvider" --tag=config`

olarak publish ederseniz netgsm için config oluşturulacaktır.

**Comment by frkcn** [comment]
Hata mesajı yeni versiyonda güncellendi. 2.1.1 versiyonuna güncelleyebilirsiniz.
