### ISSUE TITLE
InvalidArgumentException: Driver [TarfinLabs\Netgsm\NetGsmChannel] not supported

### ISSUE THREAD

**Issue by okancelik3425** [tarfin-labs/netgsm#22]
InvalidArgumentException: Driver [TarfinLabs\Netgsm\NetGsmChannel] not supported. in /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Support/Manager.php:119
Stack trace:
#0 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(109): Illuminate\Support\Manager->createDriver()
#1 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Support/Manager.php(90): Illuminate\Notifications\ChannelManager->createDriver()
#2 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\Support\Manager->driver()
#3 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable()
#4 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#5 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(109): Illuminate\Notifications\NotificationSender->withLocale()
#6 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(54): Illuminate\Notifications\NotificationSender->sendNow()
#7 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Notifications/SendQueuedNotifications.php(94): Illuminate\Notifications\ChannelManager->sendNow()
#8 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Notifications\SendQueuedNotifications->handle()
#9 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#11 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#12 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call()
#13 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call()
#14 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#15 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#17 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow()
#18 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#19 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then()
#21 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#22 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#23 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Jobs\Job->fire()
#24 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\Queue\Worker->process()
#25 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\Queue\Worker->runJob()
#26 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon()
#27 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker()
#28 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#29 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#30 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#31 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#32 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call()
#33 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#34 /home/admin/www/sitem.com/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#35 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#36 /home/admin/www/sitem.com/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run()
#37 /home/admin/www/sitem.com/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#38 /home/admin/www/sitem.com/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#39 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#40 /home/admin/www/sitem.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#41 /home/admin/www/sitem.com/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#42 {main}

**Comment by okancelik3425** [comment]
Lokalde bir problem yok ama production da bu hatayı alıyorum nedendir acaba ?

**Comment by okancelik3425** [comment]
laravel versiyon 7.3
"tarfin-labs/netgsm": "2.1.2",
php version : 7.4.14

**Comment by frkcn** [comment]
Composer problemi gibi görünüyor. 

`composer dump-autoload` komutunu çalıştırmayı deneyebilir misiniz?

Eğer düzelmezse vendor klasörünü silip tekrar `composer update` ya da `composer install` komutuyla yüklemeyi deneyin.

**Comment by okancelik3425** [comment]
3-5 kez söylediğini çözümü denedim. Ama aynı hatayı alıyorum. :(

**Comment by frkcn** [comment]
`php artisan config:clear` komutunu çalıştırmayı da deneyebilir misiniz? Bu sorun paketten ziyade laravel problemi gibi görünüyor.
