### ISSUE TITLE
Example Pages

### ISSUE THREAD

**Issue by bskscmn** [tarfin-labs/netgsm#3]
Thank you for creating this package. It was needed.
 Unfortunately, I couldn't figure out how to use it.

I tried to use `Netgsm::sendSms($netgsmMessage)` but got an error which says I can not call the method statically. So I tried : 

`$sms = new Netgsm();`
`$jobID = $sms->sendSms($netgsmMessage);`

I discovered that I need to send parameters (at least 1: client) 
Also I need to define an object for $netgsmMessage  

Finally I am confused about how to use this package. 
Could you please describe or submit some example pages to show the steps.

Thanks.

**Comment by frkcn** [comment]
Hi,

I'm aware, we did not mention in the documentation. You need to add this code line in each of your notifiable user models.

```php
public function routeNotificationForNetgsm($notification)
{
    return preg_replace('/\D/', '', $this->phone);
}
```

After defining the notification rule for netgsm in your user model, You can start sending SMS adding these code blocks in your notification class.

```php
use TarfinLabs\Netgsm\NetgsmChannel;
use TarfinLabs\Netgsm\NetgsmSmsMessage;

public function via($notifiable)
{
    return [NetgsmChannel::class];
}
 
public function toNetgsm($notifiable)
{
    return new NetgsmSmsMessage(''Hello, World!');
}
```

We will improve the documentation soon.
