### ISSUE TITLE
How to use package to get credit

### ISSUE THREAD

**Issue by hmohamedbaims** [tarfin-labs/netgsm#33]
- Netgsm Package Version: 4.4
- Laravel Version: 8
- PHP Version: 7.4

**Describe the bug**
thanks for package i keep try use this methods same documnetation Netgsm::getCredit();
        Netgsm::getAvailablePackages(); but i keep get this error Using $this when not in object context => vendor/tarfin-labs/netgsm/src/Netgsm.php line 113 can you please give me good example how to use the package thanks for support

**Steps To Reproduce**

**Comment by tkaratug** [comment]
Hi @hmohamedbaims 

Thanks for opening this issue and showing interest in using our package. To use the methods you're asking about, please follow the installation instructions provided in the documentation. Be sure you set the Netgsm credentials in the `.env` file and publish the `netgsm.php` config file.

If you have any further questions or encounter any issues while following the documentation, don't hesitate to let us know by opening a new issue or commenting on this one.

Thanks again for using our package and we hope it helps you in your project!

Best regards,
@tkaratug

**Comment by aysetas** [comment]
Hi @tkaratug 

In my project I had Netgsm::getCredit(); I used it was working but now NETGSM Error message: Invalid username, password or your user does not have API access permission. I get the error. Instead, when I add a constant value, smsm is sent. So there is no problem in .env and config/netgsm.php. Can you help with this?
