### ISSUE TITLE
v2.1.2 - Php version 

### ISSUE THREAD

**Issue by galiperkin** [tarfin-labs/netgsm#35]
**Is your feature request related to a problem? Please describe.**
Could you please add support for php8 on composer.json
**Describe the solution you'd like**
You may add `"php": "^7.2.5|^8.0",` to composer.json

**Additional context**
I am running a laravel7 application with php 8.0.29

Thank you in advance.

**Comment by tkaratug** [comment]
Hi @galiperkin,

Thank you for reaching out and expressing your interest in adding support for Laravel 7 to our package.

As you mentioned, our package currently supports Laravel from version 8 onwards. The decision to start supporting Laravel from version 8 was made to take advantage of the latest features, improvements, and security enhancements introduced in the newer versions of the framework. Additionally, Laravel 7 has reached its end of life and is no longer actively maintained by the Laravel team.

Maintaining backward compatibility with older versions can be a complex and time-consuming task, and it might hinder our ability to leverage the latest Laravel features effectively. Therefore, we've chosen to focus on providing the best possible support for the latest Laravel releases.

However, we encourage you to fork the repository and work on adding Laravel 7 support if you find it essential for your project or if other users in the community would benefit from it. By forking the package, you can customize it to meet your specific needs, ensuring it remains compatible with the Laravel 7 environment you are using.

Thank you once again for your understanding and support. If you have any other questions or need further assistance, please don't hesitate to let us know.

Best regards,
Tarfin Team

**Comment by frkcn** [comment]
@galiperkin Hi, you can use v3 of the package which already supports Laravel 7.
